export default [
	{
		login: `kumarabd`,
		id: 10404724,
		node_id: `MDQ6VXNlcjEwNDA0NzI0`,
		avatar_url: `https://avatars2.githubusercontent.com/u/10404724?v=4`,
		gravatar_id: ``,
		url: `https://api.github.com/users/kumarabd`,
		html_url: `https://github.com/kumarabd`,
		followers_url: `https://api.github.com/users/kumarabd/followers`,
		following_url: `https://api.github.com/users/kumarabd/following{/other_user}`,
		gists_url: `https://api.github.com/users/kumarabd/gists{/gist_id}`,
		starred_url: `https://api.github.com/users/kumarabd/starred{/owner}{/repo}`,
		subscriptions_url: `https://api.github.com/users/kumarabd/subscriptions`,
		organizations_url: `https://api.github.com/users/kumarabd/orgs`,
		repos_url: `https://api.github.com/users/kumarabd/repos`,
		events_url: `https://api.github.com/users/kumarabd/events{/privacy}`,
		received_events_url: `https://api.github.com/users/kumarabd/received_events`,
		type: `User`,
		site_admin: false,
	},
	{
		login: `shanthanaroja`,
		id: 62417823,
		node_id: `MDQ6VXNlcjYyNDE3ODIz`,
		avatar_url: `https://avatars1.githubusercontent.com/u/62417823?v=4`,
		gravatar_id: ``,
		url: `https://api.github.com/users/shanthanaroja`,
		html_url: `https://github.com/shanthanaroja`,
		followers_url: `https://api.github.com/users/shanthanaroja/followers`,
		following_url: `https://api.github.com/users/shanthanaroja/following{/other_user}`,
		gists_url: `https://api.github.com/users/shanthanaroja/gists{/gist_id}`,
		starred_url: `https://api.github.com/users/shanthanaroja/starred{/owner}{/repo}`,
		subscriptions_url: `https://api.github.com/users/shanthanaroja/subscriptions`,
		organizations_url: `https://api.github.com/users/shanthanaroja/orgs`,
		repos_url: `https://api.github.com/users/shanthanaroja/repos`,
		events_url: `https://api.github.com/users/shanthanaroja/events{/privacy}`,
		received_events_url: `https://api.github.com/users/shanthanaroja/received_events`,
		type: `User`,
		site_admin: false,
	},
	{
		login: `Arindamdeb2000`,
		id: 20836715,
		node_id: `MDQ6VXNlcjIwODM2NzE1`,
		avatar_url: `https://avatars2.githubusercontent.com/u/20836715?v=4`,
		gravatar_id: ``,
		url: `https://api.github.com/users/Arindamdeb2000`,
		html_url: `https://github.com/Arindamdeb2000`,
		followers_url: `https://api.github.com/users/Arindamdeb2000/followers`,
		following_url: `https://api.github.com/users/Arindamdeb2000/following{/other_user}`,
		gists_url: `https://api.github.com/users/Arindamdeb2000/gists{/gist_id}`,
		starred_url: `https://api.github.com/users/Arindamdeb2000/starred{/owner}{/repo}`,
		subscriptions_url: `https://api.github.com/users/Arindamdeb2000/subscriptions`,
		organizations_url: `https://api.github.com/users/Arindamdeb2000/orgs`,
		repos_url: `https://api.github.com/users/Arindamdeb2000/repos`,
		events_url: `https://api.github.com/users/Arindamdeb2000/events{/privacy}`,
		received_events_url: `https://api.github.com/users/Arindamdeb2000/received_events`,
		type: `User`,
		site_admin: false,
	},
	{
		login: `goandreus`,
		id: 24356603,
		node_id: `MDQ6VXNlcjI0MzU2NjAz`,
		avatar_url: `https://avatars0.githubusercontent.com/u/24356603?v=4`,
		gravatar_id: ``,
		url: `https://api.github.com/users/goandreus`,
		html_url: `https://github.com/goandreus`,
		followers_url: `https://api.github.com/users/goandreus/followers`,
		following_url: `https://api.github.com/users/goandreus/following{/other_user}`,
		gists_url: `https://api.github.com/users/goandreus/gists{/gist_id}`,
		starred_url: `https://api.github.com/users/goandreus/starred{/owner}{/repo}`,
		subscriptions_url: `https://api.github.com/users/goandreus/subscriptions`,
		organizations_url: `https://api.github.com/users/goandreus/orgs`,
		repos_url: `https://api.github.com/users/goandreus/repos`,
		events_url: `https://api.github.com/users/goandreus/events{/privacy}`,
		received_events_url: `https://api.github.com/users/goandreus/received_events`,
		type: `User`,
		site_admin: false,
	},
];
