export default {
	login: `kishore007k`,
	id: 34863222,
	node_id: `MDQ6VXNlcjM0ODYzMjIy`,
	avatar_url: `https://avatars1.githubusercontent.com/u/34863222?v=4`,
	gravatar_id: ``,
	url: `https://api.github.com/users/kishore007k`,
	html_url: `https://github.com/kishore007k`,
	followers_url: `https://api.github.com/users/kishore007k/followers`,
	following_url: `https://api.github.com/users/kishore007k/following{/other_user}`,
	gists_url: `https://api.github.com/users/kishore007k/gists{/gist_id}`,
	starred_url: `https://api.github.com/users/kishore007k/starred{/owner}{/repo}`,
	subscriptions_url: `https://api.github.com/users/kishore007k/subscriptions`,
	organizations_url: `https://api.github.com/users/kishore007k/orgs`,
	repos_url: `https://api.github.com/users/kishore007k/repos`,
	events_url: `https://api.github.com/users/kishore007k/events{/privacy}`,
	received_events_url: `https://api.github.com/users/kishore007k/received_events`,
	type: `User`,
	site_admin: false,
	name: `kishore kumar`,
	company: `@Layer5io`,
	blog: ``,
	location: `Chennai`,
	email: null,
	hireable: true,
	bio: `#Python\r\n#HTML\r\n#CSS\r\n#JavaScript\r\n#React JS`,
	twitter_username: `kishorekumarst1`,
	public_repos: 33,
	public_gists: 0,
	followers: 4,
	following: 8,
	created_at: `2017-12-26T15:00:27Z`,
	updated_at: `2020-10-21T11:47:34Z`,
};
